version: '2'
services:

  php:
      image: jguillermo/demo-app:php
      volumes:
        - ./app/:/var/www/html
      ports:
        - 8085:80

  mysql:
    image: jguillermo/demo-app:mysql
    environment:
      MYSQL_ROOT_PASSWORD: toord
      MYSQL_USER : root
      MYSQL_DATABASE: dbproject
    ports:
      - 3369:3306
    volumes:
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
