services:

    _defaults:
        autowire: true
        autoconfigure: true

    Misa\Users\Infrastructure\Ui\UsersBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']


    ###    services

    #user
    Misa\Users\Application\Services\User\ListService: ~
    Misa\Users\Application\Services\User\MngService: ~

    Misa\Users\Application\Services\Employee\ListService: ~
    Misa\Users\Application\Services\Employee\MngService: ~


    ###   repository
    Misa\Users\Domain\UserRepository: '@users.users.rep'
    Misa\Users\Domain\Employee\EmployeeRepository: '@users.employee.rep'

    users.users.rep:
        class: Misa\Users\Infrastructure\Persistence\Doctrine\UserDbRepository
        arguments: {$entityName: 'Misa\Users\Domain\User'}
        autowire: true

    users.employee.rep:
        class: Misa\Users\Infrastructure\Persistence\Doctrine\EmployeeDbRepository
        arguments: {$entityName: 'Misa\Users\Domain\Employee\Employee'}
        autowire: true

    ### presentation
    Misa\Users\Presentation\UserPresentation: ~
    Misa\Users\Presentation\EmployeePresentation: ~

    my.graph.resolver.character:
        class: Misa\Users\Infrastructure\Ui\UsersBundle\Resolver\CharacterResolver
        arguments:
            - "@overblog_graphql.type_resolver"
        tags:
            - { name: overblog_graphql.resolver, alias: "character_type", method: "resolveType" }
            - { name: overblog_graphql.resolver, alias: "character_friends", method: "resolveFriends" }
            - { name: overblog_graphql.resolver, alias: "character_hero", method: "resolveHero" }
            - { name: overblog_graphql.resolver, alias: "character_human", method: "resolveHuman" }
            - { name: overblog_graphql.resolver, alias: "character_droid", method: "resolveDroid" }






